-- 1 up
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: website; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS website;




--
-- Name: domains; Type: TABLE; Schema: website; Owner: -
--

CREATE TABLE website.domains (
    domainid bigint NOT NULL,
    websiteid bigint NOT NULL,
    domainname character varying(191) NOT NULL,
    customerid bigint,
    incert boolean DEFAULT true NOT NULL
);


--
-- Name: domains_domainid_seq; Type: SEQUENCE; Schema: website; Owner: -
--

ALTER TABLE website.domains ALTER COLUMN domainid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME website.domains_domainid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: phpconfigs; Type: TABLE; Schema: website; Owner: -
--

CREATE TABLE website.phpconfigs (
    phpconfigid bigint NOT NULL,
    phpconfig text,
    websiteid bigint NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: TABLE phpconfigs; Type: COMMENT; Schema: website; Owner: -
--

COMMENT ON TABLE website.phpconfigs IS 'PHP-FPM pool configuration, merged with .php.conf';


--
-- Name: phpconfigs_phpconfigid_seq; Type: SEQUENCE; Schema: website; Owner: -
--

ALTER TABLE website.phpconfigs ALTER COLUMN phpconfigid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME website.phpconfigs_phpconfigid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: serverextras; Type: TABLE; Schema: website; Owner: -
--

CREATE TABLE website.serverextras (
    serverextraid bigint NOT NULL,
    configextra text,
    websiteid bigint NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: TABLE serverextras; Type: COMMENT; Schema: website; Owner: -
--

COMMENT ON TABLE website.serverextras IS 'Extra configuration directives for Apache/Nginx';


--
-- Name: serverextras_serverextraid_seq; Type: SEQUENCE; Schema: website; Owner: -
--

ALTER TABLE website.serverextras ALTER COLUMN serverextraid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME website.serverextras_serverextraid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servers; Type: TABLE; Schema: website; Owner: -
--

CREATE TABLE website.servers (
    serverid bigint NOT NULL,
    hostname character varying(255) NOT NULL,
    jailname character varying(255),
    servertypeid bigint,
    default_ip4 inet,
    default_ip6 inet
);


--
-- Name: TABLE servers; Type: COMMENT; Schema: website; Owner: -
--

COMMENT ON TABLE website.servers IS 'Physical/virtual servers with default IP addresses';


--
-- Name: servers_serverid_seq; Type: SEQUENCE; Schema: website; Owner: -
--

ALTER TABLE website.servers ALTER COLUMN serverid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME website.servers_serverid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servertypes; Type: TABLE; Schema: website; Owner: -
--

CREATE TABLE website.servertypes (
    servertypeid bigint NOT NULL,
    servertypename character varying(255) NOT NULL
);


--
-- Name: TABLE servertypes; Type: COMMENT; Schema: website; Owner: -
--

COMMENT ON TABLE website.servertypes IS 'Server software types (nginx, apache2, mojolicious, etc.)';


--
-- Name: servertypes_servertypeid_seq; Type: SEQUENCE; Schema: website; Owner: -
--

ALTER TABLE website.servertypes ALTER COLUMN servertypeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME website.servertypes_servertypeid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shells; Type: TABLE; Schema: website; Owner: -
--

CREATE TABLE website.shells (
    shellid bigint NOT NULL,
    shell character varying(255)
);


--
-- Name: shells_shellid_seq; Type: SEQUENCE; Schema: website; Owner: -
--

ALTER TABLE website.shells ALTER COLUMN shellid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME website.shells_shellid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: websites; Type: TABLE; Schema: website; Owner: -
--

CREATE TABLE website.websites (
    websiteid bigint NOT NULL,
    home text NOT NULL,
    primarydomain bigint,
    customerid bigint,
    serverid bigint,
    passwordid bigint,
    certificateid bigint,
    shellid bigint,
    ip4 inet,
    ip6 inet,
    ip_only boolean DEFAULT false NOT NULL,
    redirecturl character varying(255),
    active smallint DEFAULT 1,
    web_usage bigint DEFAULT 0 NOT NULL
);


--
-- Name: COLUMN websites.ip4; Type: COMMENT; Schema: website; Owner: -
--

COMMENT ON COLUMN website.websites.ip4 IS 'IPv4 address override (null = use server default)';


--
-- Name: COLUMN websites.ip6; Type: COMMENT; Schema: website; Owner: -
--

COMMENT ON COLUMN website.websites.ip6 IS 'IPv6 address override (null = use server default)';


--
-- Name: COLUMN websites.ip_only; Type: COMMENT; Schema: website; Owner: -
--

COMMENT ON COLUMN website.websites.ip_only IS 'Bind to IP only, no hostname (catch-all for domain parking)';


--
-- Name: websites_websiteid_seq; Type: SEQUENCE; Schema: website; Owner: -
--

ALTER TABLE website.websites ALTER COLUMN websiteid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME website.websites_websiteid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: domains domainname_uq; Type: CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.domains
    ADD CONSTRAINT domainname_uq UNIQUE (domainname);


--
-- Name: domains domains_pk; Type: CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.domains
    ADD CONSTRAINT domains_pk PRIMARY KEY (domainid);


--
-- Name: phpconfigs phpconfigs_pk; Type: CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.phpconfigs
    ADD CONSTRAINT phpconfigs_pk PRIMARY KEY (phpconfigid);


--
-- Name: serverextras serverextras_pk; Type: CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.serverextras
    ADD CONSTRAINT serverextras_pk PRIMARY KEY (serverextraid);


--
-- Name: servers servers_pk; Type: CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.servers
    ADD CONSTRAINT servers_pk PRIMARY KEY (serverid);


--
-- Name: servertypes servertypes_pk; Type: CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.servertypes
    ADD CONSTRAINT servertypes_pk PRIMARY KEY (servertypeid);


--
-- Name: shells shells_pk; Type: CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.shells
    ADD CONSTRAINT shells_pk PRIMARY KEY (shellid);


--
-- Name: websites webservices_pk; Type: CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.websites
    ADD CONSTRAINT webservices_pk PRIMARY KEY (websiteid);


--
-- Name: domains domains_customerid_fk; Type: FK CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.domains
    ADD CONSTRAINT domains_customerid_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: domains domains_websiteid_fk; Type: FK CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.domains
    ADD CONSTRAINT domains_websiteid_fk FOREIGN KEY (websiteid) REFERENCES website.websites(websiteid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: phpconfigs phpconfigs_websiteid_fk; Type: FK CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.phpconfigs
    ADD CONSTRAINT phpconfigs_websiteid_fk FOREIGN KEY (websiteid) REFERENCES website.websites(websiteid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: serverextras serverextras_websiteid_fk; Type: FK CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.serverextras
    ADD CONSTRAINT serverextras_websiteid_fk FOREIGN KEY (websiteid) REFERENCES website.websites(websiteid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: servers servers_servertypeid_fk; Type: FK CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.servers
    ADD CONSTRAINT servers_servertypeid_fk FOREIGN KEY (servertypeid) REFERENCES website.servertypes(servertypeid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: websites websites_certificateid_fk; Type: FK CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.websites
    ADD CONSTRAINT websites_certificateid_fk FOREIGN KEY (certificateid) REFERENCES certificate.certificates(certificateid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: websites websites_customerid_fk; Type: FK CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.websites
    ADD CONSTRAINT websites_customerid_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: websites websites_passwordid_fk; Type: FK CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.websites
    ADD CONSTRAINT websites_passwordid_fk FOREIGN KEY (passwordid) REFERENCES account.passwords(passwordid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: websites websites_primarydomain_fk; Type: FK CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.websites
    ADD CONSTRAINT websites_primarydomain_fk FOREIGN KEY (primarydomain) REFERENCES website.domains(domainid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: websites websites_serverid_fk; Type: FK CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.websites
    ADD CONSTRAINT websites_serverid_fk FOREIGN KEY (serverid) REFERENCES website.servers(serverid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: websites websites_shellid_fk; Type: FK CONSTRAINT; Schema: website; Owner: -
--

ALTER TABLE ONLY website.websites
    ADD CONSTRAINT websites_shellid_fk FOREIGN KEY (shellid) REFERENCES website.shells(shellid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

-- 1 down
DROP SCHEMA IF EXISTS website CASCADE;
